name: Seedwing Dependency Enforcer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  enforcer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check dependency tree against provided policies
        uses: seedwing-io/enforcer-action@3492598daf699933dac7e5361e470b5f83ba1c7e
        with:
          policy-dir: enforcer.dog
          enforcer-config: .enforcer.yaml
          source: pom.xml
