name: Seedwing Dependency Enforcer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  enforcer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check dependency tree against provided policies
        uses: seedwing-io/enforcer-action@4ae4243957aa94d636a3095a80a19fc41272265d
        with:
          policy-dir: enforcer.dog
          enforcer-config: .enforcer.yaml
          source: pom.xml
