name: Seedwing Dependency Enforcer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  enforcer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check dependency tree against provided policies
        uses: seedwing-io/enforcer-action@3e7bc84d100a58af996ecb3d96583864701943cc
        with:
          policy-dir: enforcer.dog
          enforcer-config: .enforcer.yaml
          source: pom.xml
